# Site settings
name: Sunil Kumar
title: Sunil Kumar | Business Analyst
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://sunkumx.github.io/
baseurl: ''
email: ping.sunilk@gmail.com
cover: https://sunkumx.github.io/img/og.png
logo: https://sunkumx.github.io/img/emojis/technologist.png
resume: https://sunkumx.github.io/resume.pdf
social:
  - title: email
    url: mailto:ping.sunilk@gmail.com
  - title: tableau public profile
    url: https://public.tableau.com/app/profile/sunil.kumar.r.m/vizzes
  - title: hackerrank
    url: https://www.hackerrank.com/profile/sunkumx
  - title: medium
    url: https://medium.com/@sunkumx
  - title: github
    url: https://github.com/sunkumx
  - title: linkedin
    url: https://www.linkedin.com/in/sunkumx

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
